Use custom icon for `SelectField`
Qualifyze/design-system pull request #103
Opened 2021-07-31 11:58 UTC by gregoralbrecht

So far, we've been using the default dropdown indicator icon from
`react-select` in our `SelectField` component. It's very easy to use our
own icons, though, so let's do it.

## Before
![image](https://user-images.githubusercontent.com/6179211/127739176-07f354ae-e9cc-4196-b508-b29154d7f8f5.png)

## After
![image](https://user-images.githubusercontent.com/6179211/127739178-5e88114c-9a08-4a33-b5d6-2e64bdbc54d5.png)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualifyze/design-system/103)

2021-08-02 05:45 UTC, falco953 requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/103)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[src/components/SelectField/index.jsx, line 64 at r1](https://reviewable.io/reviews/qualifyze/design-system/103#-Mg4O2Pj3MEruH34hFtw:-Mg4O2Pj3MEruH34hFtx:byr9o5s) ([raw file](https://github.com/qualifyze/design-system/blob/9f59e8860007a5e6ba284645d3d7b104633730d0/src/components/SelectField/index.jsx#L64)):*
> ```JavaScript
> 
> // eslint-disable-next-line react/prop-types
> const DropdownIndicator = ({ innerProps }) => {
> ```

why do you destructure the props here? Why not just pass them down?


<!-- Sent from Reviewable.io -->

2021-08-02 09:04 UTC, gregoralbrecht reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/103)* status: all files reviewed, 1 unresolved discussion (waiting on @falco953)

___
*[src/components/SelectField/index.jsx, line 64 at r1](https://reviewable.io/reviews/qualifyze/design-system/103#-Mg4O2Pj3MEruH34hFtw:-Mg55aUq0F5jO0C_XT-b:b-opc0mt) ([raw file](https://github.com/qualifyze/design-system/blob/9f59e8860007a5e6ba284645d3d7b104633730d0/src/components/SelectField/index.jsx#L64)):*
<details><summary><i>Previously, falco953 (Falco Trompeter) wrote…</i></summary><blockquote>

why do you destructure the props here? Why not just pass them down?
</blockquote></details>

What would be the reason to pass them all down? `innerProps` is all they need: https://react-select.com/components#replacing-components


<!-- Sent from Reviewable.io -->

2021-08-02 13:45 UTC, sirJiggles approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/103)* status: all files reviewed, 1 unresolved discussion (waiting on @falco953)



<!-- Sent from Reviewable.io -->

2021-08-03 16:10 UTC, falco953 approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht)

___
*[src/components/SelectField/index.jsx, line 64 at r1](https://reviewable.io/reviews/qualifyze/design-system/103#-Mg4O2Pj3MEruH34hFtw:-MgBlqfND0SVuVsXr9FX:b-ylksmd) ([raw file](https://github.com/qualifyze/design-system/blob/9f59e8860007a5e6ba284645d3d7b104633730d0/src/components/SelectField/index.jsx#L64)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

What would be the reason to pass them all down? `innerProps` is all they need: https://react-select.com/components#replacing-components
</blockquote></details>

Ah ok, then all good


<!-- Sent from Reviewable.io -->

2021-08-03 16:10 UTC, merged