Restore icon tone property
Qualifyze/design-system pull request #172
Opened 2021-08-20 23:41 UTC by vubogovich

## What

Restore icon `tone` property so it overrides the provided color.

## Why

It's currently ignored. There is an interesting comment on `color` property:

```
We disabled the next rule on color, because we don't want to give it any default value
because it will overwrite any tone given by the user
```

However, currently `tone` is always overridden by the `color` property as the latter is defaulted to `currentColor`.
The problem is that implementing it as stated by the comment would be a breaking change.

Alternative: remove tone property completely.

## Who is affected

Library consumers who provided both `tone` and `color` and ignored the fact that `tone` is completely ignored.

2021-08-22 14:22 UTC, gregoralbrecht requested changes
> ```
> color={props.tone ? undefined : color}
> ```

Oh wow can't believe we've missed that lately, thanks for the PR! I believe the correct way to use Icon would be with a `tone` prop, so this seems correct to:
```
color={props.tone ?? `currentColor`}
```

I don't think we should expose both `tone` and `color` props. Tone is the more opinionated color and if someone wants to use color they can do it via `currentColor`

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/172#-:-MhiDsys04AK0Goa1IZL:bywz6b9)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @vubogovich)



<!-- Sent from Reviewable.io -->

2021-08-23 12:20 UTC, vubogovich reviewed
We have a number of places in `website`, `legacy` and `request-audit` packages which uses `color` prop, so removing it now would be a breaking change for us not mentioning that the design system is open-sourced now.
The intention of this PR is to keep it backward compatible.
Marked `color` as deprecated and we can make the desired major changes once we collect enough of them.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/172#-:-MhmvIcK-a4e4o0-xIAp:b-7mocgu)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @vubogovich)



<!-- Sent from Reviewable.io -->

2021-08-23 16:52 UTC, gregoralbrecht requested changes
It's really sad we lost the git history for that because I'd love to understand how `color` crept in here. 

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/172#-:-MhnfZcU0Z5X-Y63DQ_f:bw0p62p)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @vubogovich)

___
*[src/components/Icon/index.jsx, line 70 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-MhnvC0pEuPbNUEQzxRU:-MhnvC0pEuPbNUEQzxRV:b-gzob85) ([raw file](https://github.com/qualifyze/design-system/blob/2ffb63b915ec89ef7b00a0af4159d0682ca82917/src/components/Icon/index.jsx#L70)):*
> ```JavaScript
>       info: {
>         color: 'secondary.600',
>       },
> ```

To make using `currentColor` a little easier, I believe we should add another option here:
```
current: {
    color: 'currentColor',
}
```
___
*[src/components/Icon/index.jsx, line 84 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-MhntZQb0bCODteDyb9N:-MhntZQb0bCODteDyb9O:b-mx0m04) ([raw file](https://github.com/qualifyze/design-system/blob/2ffb63b915ec89ef7b00a0af4159d0682ca82917/src/components/Icon/index.jsx#L84)):*
> ```JavaScript
>       {...props}
>       viewBox="0 0 92 92"
>       color={props.tone ? undefined : color}
> ```

I think we're good to go with just `color={color}` and have it be undefined by default.
___
*[src/components/Icon/index.jsx, line 96 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-Mhntgv58skFrZPcTv4T:-Mhntgv58skFrZPcTv4U:b-rmfrzr) ([raw file](https://github.com/qualifyze/design-system/blob/2ffb63b915ec89ef7b00a0af4159d0682ca82917/src/components/Icon/index.jsx#L96)):*
> ```JavaScript
>   size: PropTypes.oneOf(['tiny', 'small', 'standard', 'large', 'gigantic']),
>   /**
>    * @deprecated Please use `tone` property instead, or set the color via `sx`.
> ```

Nice idea to deprecate it properly! `sx` will also be deprecated at some point, so let's already use this explanation instead:
```
Please use the `tone` prop or set `tone="current"` and set the color on a containing element.
``` 
___
*[src/components/Icon/index.jsx, line 114 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-MhnuBQI4adKecysJHhW:-MhnuBQI4adKecysJHhX:b-obkb9s) ([raw file](https://github.com/qualifyze/design-system/blob/2ffb63b915ec89ef7b00a0af4159d0682ca82917/src/components/Icon/index.jsx#L114)):*
> ```JavaScript
> Icon.defaultProps = {
>   size: 'standard',
>   color: 'currentColor',
> ```

This seems rather confusing because we're now using `color = currentColor` but only use it if `tone` isn't set? IMHO we can leave these as they were and they will work as expected: If you provide `tone`, we will use it. If you provide `color`, it will override `tone`.
I'm aware it's a suboptimal API but probably fine for now.


<!-- Sent from Reviewable.io -->

2021-08-23 22:35 UTC, vubogovich reviewed
It's sad we didn't move design system files with history, but the previous repo is still there. You can checkout it using revision `4ee870d4` and find the commit in Qualifyze/qualifyze#1144.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/172#-:-Mhp6XcH4jLUB-JjdqGm:b-16sy2b)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @gregoralbrecht and @vubogovich)

___
*[src/components/Icon/index.jsx, line 96 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-Mhntgv58skFrZPcTv4T:-Mhp87h30YSosY8QwUek:b1i7dkc) ([raw file](https://github.com/qualifyze/design-system/blob/2ffb63b915ec89ef7b00a0af4159d0682ca82917/src/components/Icon/index.jsx#L96)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Nice idea to deprecate it properly! `sx` will also be deprecated at some point, so let's already use this explanation instead:
```
Please use the `tone` prop or set `tone="current"` and set the color on a containing element.
``` 
</blockquote></details>

The suggestions are good but for backward compatibility the suggested new tone `current` should be a default one.
___
*[src/components/Icon/index.jsx, line 114 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-MhnuBQI4adKecysJHhW:-Mhp8P6v2sgbTXjyjost:bj53t4n) ([raw file](https://github.com/qualifyze/design-system/blob/2ffb63b915ec89ef7b00a0af4159d0682ca82917/src/components/Icon/index.jsx#L114)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This seems rather confusing because we're now using `color = currentColor` but only use it if `tone` isn't set? IMHO we can leave these as they were and they will work as expected: If you provide `tone`, we will use it. If you provide `color`, it will override `tone`.
I'm aware it's a suboptimal API but probably fine for now.
</blockquote></details>

`currentColor` is just moved from component render to the defaultProps, not really a functional change among others. We can make `color` overriding `tone` only if the latter default value is `current` so `<Icon name="..." />` works as before.


<!-- Sent from Reviewable.io -->

2021-08-24 09:13 UTC, gregoralbrecht requested changes
Looks like I messed this one up :eyes: Looking forward to have tests for this stuff!

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/172#-:-MhrQ5HCB7T0rhbgG5O7:b-kwts41)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @vubogovich)

___
*[src/components/Icon/index.jsx, line 96 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-Mhntgv58skFrZPcTv4T:-MhrQFdW4B91j6lsx1Q0:bjjkop6) ([raw file](https://github.com/qualifyze/design-system/blob/b7691d79385247c938aaae0ef266ab9c9db03e5f/src/components/Icon/index.jsx#L96)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

The suggestions are good but for backward compatibility the suggested new tone `current` should be a default one.
</blockquote></details>

Yeah we can do that, not too sure of all implications but that works.
___
*[src/components/Icon/index.jsx, line 114 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-MhnuBQI4adKecysJHhW:-MhrQQGeDZhxl2wX9vr9:bxvejwb) ([raw file](https://github.com/qualifyze/design-system/blob/b7691d79385247c938aaae0ef266ab9c9db03e5f/src/components/Icon/index.jsx#L114)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

`currentColor` is just moved from component render to the defaultProps, not really a functional change among others. We can make `color` overriding `tone` only if the latter default value is `current` so `<Icon name="..." />` works as before.
</blockquote></details>

Wait, not sure if we're on the same page yet.

This is what we're aiming for:

Option A: Set `tone` => We use `tone`, defaults to `current`
Option B: Set `color` => We use `color`

So `color` needs to be undefined by default so that option A works without any magic here


<!-- Sent from Reviewable.io -->

2021-08-24 10:28 UTC, vubogovich reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/172)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @gregoralbrecht and @vubogovich)

___
*[src/components/Icon/index.jsx, line 70 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-MhnvC0pEuPbNUEQzxRU:-MhrgdYK3XbOFEiDBGHi:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b7691d79385247c938aaae0ef266ab9c9db03e5f/src/components/Icon/index.jsx#L70)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

To make using `currentColor` a little easier, I believe we should add another option here:
```
current: {
    color: 'currentColor',
}
```
</blockquote></details>

Done.
___
*[src/components/Icon/index.jsx, line 84 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-MhntZQb0bCODteDyb9N:-Mhrgepc2JmCCe52vwBa:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b7691d79385247c938aaae0ef266ab9c9db03e5f/src/components/Icon/index.jsx#L84)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I think we're good to go with just `color={color}` and have it be undefined by default.
</blockquote></details>

Done.
___
*[src/components/Icon/index.jsx, line 96 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-Mhntgv58skFrZPcTv4T:-MhrgjQr8AeG9oNKntll:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b7691d79385247c938aaae0ef266ab9c9db03e5f/src/components/Icon/index.jsx#L96)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Yeah we can do that, not too sure of all implications but that works.
</blockquote></details>

Done.
___
*[src/components/Icon/index.jsx, line 114 at r2](https://reviewable.io/reviews/qualifyze/design-system/172#-MhnuBQI4adKecysJHhW:-MhrgkIpBjgSF_pW1V3e:bw7zfab) ([raw file](https://github.com/qualifyze/design-system/blob/b7691d79385247c938aaae0ef266ab9c9db03e5f/src/components/Icon/index.jsx#L114)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Wait, not sure if we're on the same page yet.

This is what we're aiming for:

Option A: Set `tone` => We use `tone`, defaults to `current`
Option B: Set `color` => We use `color`

So `color` needs to be undefined by default so that option A works without any magic here
</blockquote></details>

Please check the changes.


<!-- Sent from Reviewable.io -->

2021-08-24 11:13 UTC, gregoralbrecht approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)



<!-- Sent from Reviewable.io -->

2021-08-24 11:18 UTC, merged