Re-implement loading indicator for `TextLinkButton`
Qualifyze/design-system pull request #179
Opened 2021-09-20 10:14 UTC by gregoralbrecht

We recently noticed that `TextLinkButton` is missing the same visual loading indicator we have for `Button`. This was added in #176, but in a way that introduced avoidable complexity and needed fixing in #177. This PR here first resets `TextLinkButton` to a state before the two mentioned PRs and then re-implements the desired changes.

# Why?
The current implementation has a few flaws:

1. We lose the `ref` on `TextLinkButton` because it's never forwarded. This is fixed by adding the changes to the underlying `TextLink` instead, where we take care of forwarding the `ref`.
2. We mess up the semantics because `TextLinkButton` currently needs an additional wrapper. Fixed in the same way as above.
3. The complexity that needed to be addressed in #177 is entirely avoidable—the same fix as above.
4. This somehow broke the `font-size` when using `TextLinkButton` inside `Actions` (see screenshot below)

## Correct `font-size`
![image](https://user-images.githubusercontent.com/6179211/133986572-8ddbe372-fe80-4e21-a19b-7977c0bad40a.png)

## Current, incorrect `font-size`
![image](https://user-images.githubusercontent.com/6179211/133986588-2eb366f4-8bd2-4a6b-9ebc-983dcd6b6ffa.png)

2021-09-21 15:03 UTC, phjardas requested changes
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/179)* status: all files reviewed, 3 unresolved discussions (waiting on @gregoralbrecht)

___
*[src/components/Button/index.jsx, line 76 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7ripC1fbbnupPR_MM:-Mk7ripD1mQ0sKHO8sPg:bitvawg) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/Button/index.jsx#L76)):*
> ```JavaScript
> )
> 
> export const Loader = styled.span`
> ```

Maybe export this component into a separate file? (not blocking)
___
*[src/components/TextLink/index.jsx, line 93 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7rwjQ4iu_FjnPkLWO:-Mk7rwjRCc7zw72d5IJ0:bl1xngz) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/TextLink/index.jsx#L93)):*
> ```JavaScript
>           <span />
>           <span />
>         </Loader>
> ```

Why doesn't the loader already include the spans? They are an implementation detail of the loader. Replacing the animation will become harder this way.
___
*[src/components/TextLinkButton/index.jsx, line 26 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7sNSFAUxx7BBjaKJ0:-Mk7sNSFAUxx7BBjaKJ1:b-hk3xm) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/TextLinkButton/index.jsx#L26)):*
> ```JavaScript
> TextLinkButton.propTypes = {
>   isLoading: PropTypes.bool,
>   // eslint-disable-next-line react/require-default-props
> ```

Why ignore the lint rules and not add a default of `null`?


<!-- Sent from Reviewable.io -->

2021-09-22 08:18 UTC, gregoralbrecht reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/179)* status: all files reviewed, 2 unresolved discussions (waiting on @phjardas)

___
*[src/components/Button/index.jsx, line 76 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7ripC1fbbnupPR_MM:-MkBZZyk07DhGq3Q43zb:bfrdjqb) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/Button/index.jsx#L76)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Maybe export this component into a separate file? (not blocking)
</blockquote></details>

It strictly "belongs" to the button, so I wouldn't want to move it out of here 
___
*[src/components/TextLink/index.jsx, line 93 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7rwjQ4iu_FjnPkLWO:-MkBZkM4COTAYZIsEk7i:b-5m9o7r) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/TextLink/index.jsx#L93)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Why doesn't the loader already include the spans? They are an implementation detail of the loader. Replacing the animation will become harder this way.
</blockquote></details>

There is no separate functional component and I don't yet see the need for it to abstract three spans
___
*[src/components/TextLinkButton/index.jsx, line 26 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7sNSFAUxx7BBjaKJ0:-MkBZw0d8B8jFZ-6JZ8o:b-rgqkes) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/TextLinkButton/index.jsx#L26)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Why ignore the lint rules and not add a default of `null`?
</blockquote></details>

Yeah either works, we've just disabled the linter in the past because this is transitional anyway. PropTypes will be gone in v2 because it's TS and, to me, adding default props of `null` and `undefined` isn't more or less elegant than disabling the linter. 


<!-- Sent from Reviewable.io -->

2021-09-22 11:35 UTC, phjardas reviewed
@gregoralbrecht I'm not convinced regarding the three-dots-loader component yet, but feel free to merge. :-)

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/179#-:-MkCHMEOC8gJUR8plEPI:bi50bvt)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[src/components/Button/index.jsx, line 76 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7ripC1fbbnupPR_MM:-MkCH18Q6SFW5X9XFbrm:b-uqjqcs) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/Button/index.jsx#L76)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

It strictly "belongs" to the button, so I wouldn't want to move it out of here 
</blockquote></details>

But why is it exported then and reused in another component? :thinking: 
___
*[src/components/TextLinkButton/index.jsx, line 26 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7sNSFAUxx7BBjaKJ0:-MkCHD4L9qXNKEtzkOT3:becjlxs) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/TextLinkButton/index.jsx#L26)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Yeah either works, we've just disabled the linter in the past because this is transitional anyway. PropTypes will be gone in v2 because it's TS and, to me, adding default props of `null` and `undefined` isn't more or less elegant than disabling the linter. 
</blockquote></details>

Yay for TS. I hate prop types. :laughing: 


<!-- Sent from Reviewable.io -->

2021-09-22 12:25 UTC, gregoralbrecht reviewed
Your review is still blocking :)

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/179#-:-MkCSnXB5EM-VQY26tg0:b-eyiu0k)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[src/components/Button/index.jsx, line 76 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7ripC1fbbnupPR_MM:-MkCSZkJ5cGhJvejyrCF:b-icd333) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/Button/index.jsx#L76)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

But why is it exported then and reused in another component? :thinking: 
</blockquote></details>

I mean, we could move it to a separate file within `src/components/Button` but that doesn't do much good besides creating an extra file I need to open when working with this 
___
*[src/components/TextLinkButton/index.jsx, line 26 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7sNSFAUxx7BBjaKJ0:-MkCSLKk-cgfxxK9K2mr:b-g2m95b) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/TextLinkButton/index.jsx#L26)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Yay for TS. I hate prop types. :laughing: 
</blockquote></details>

:100: agreed. Which is why I don't really care about whether we ignore them or silence them with `undefined` defaults :shrug: 


<!-- Sent from Reviewable.io -->

2021-09-24 07:32 UTC, phjardas approved these changes
Sorry! :grimacing: 

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/179#-:-MkLhsJDEHUNCUef4SSQ:b-mb9ix8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht)

___
*[src/components/Button/index.jsx, line 76 at r2](https://reviewable.io/reviews/qualifyze/design-system/179#-Mk7ripC1fbbnupPR_MM:-MkLhuk98mYcAAsJ331Y:b3l7kmv) ([raw file](https://github.com/qualifyze/design-system/blob/8ed6bd030020b1f6bbd3ecba87e927a02b99904e/src/components/Button/index.jsx#L76)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I mean, we could move it to a separate file within `src/components/Button` but that doesn't do much good besides creating an extra file I need to open when working with this 
</blockquote></details>

I don't care enough to complain further. :stuck_out_tongue_closed_eyes: 


<!-- Sent from Reviewable.io -->

2021-09-24 07:40 UTC, gregoralbrecht reviewed
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht)



<!-- Sent from Reviewable.io -->

2021-09-24 07:40 UTC, merged