New main navigation layout (QC-1275)
Qualifyze/design-system pull request #194
Opened 2021-10-01 08:29 UTC by phjardas

2021-10-15 09:44 UTC, pablosci requested changes
Looks really good, thanks for the updates. Some minor observations:
- the characters inside the avatar gets an underline in hover
- There is an idea on how we can distinguish the logout action, check Figma.
- Icon for the main action (new request) is missing
- font-size in the dropdown is different than the ones in the header navigation

2021-10-15 10:32 UTC, phjardas reviewed
@pablosci I've fixed all four issues.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194#-:-Mm2Ve-YBDimlTeYdTW-:b-ybpzxk)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @phjardas)



<!-- Sent from Reviewable.io -->

2021-10-15 14:32 UTC, pablosci requested changes
I ran the command sin the DS and monorepo and can't see the changes, I do see that the underline in the avatar is not there anymore, but if you click on the dropdown, close it and move the cursor outside it appears again.

2021-10-18 08:03 UTC, phjardas reviewed
Fixed.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194#-:-MmHQKt0CUZEtqVi1QKy:bt2vr1b)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @phjardas)



<!-- Sent from Reviewable.io -->

2021-10-18 13:52 UTC, gregoralbrecht requested changes
> Reviewed 25 of 29 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 10 unresolved discussions (waiting on @phjardas)

___
*[src/components/AppBar/Button.jsx, line 51 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmI_f2v1uIQtRxxRegm:-MmI_f2w9NiBR8VNHGm_:bfd0cfc) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/Button.jsx#L51)):*
> ```JavaScript
>   return (
>     <Button {...props}>
>       {icon && <Box sx={{ mr: 1 }}>{icon}</Box>}
> ```

AFAIK buttons can't contain `div` so this needs to be a `span`. This also makes the button bigger
![image.png](https://files.reviewableusercontent.io/images/reviewable/6179211/8Xnf5dzAA_tqQjTjeCZeMPSV/image.png)
___
*[src/components/AppBar/context.jsx, line 18 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIa-s731bvk4nkeyXz:-MmIa-s731bvk4nkeyY-:bh4db42) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/context.jsx#L18)):*
> ```JavaScript
>   const toggleExpanded = useCallback(() => setExpanded(e => !e), [])
>   const collapsed = useMediaQuery(
>     `(max-width: ${theme.breakpoints[collapseBelow]})`
> ```

We rely on our components to use the closest ancestor `theme` passed by context. Accessing it directly like this bypasses this, which will lead to unexpected behavior. If the `breakpoints.collapseBelow` value is local to this component anyway, why do we need it in the theme?
___
*[src/components/AppBar/index.jsx, line 79 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIbAmB-ymF6vFncUNi:-MmIbAmB-ymF6vFncUNj:b28e8ir) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/index.jsx#L79)):*
> ```JavaScript
> const themev2 = {
>   ...theme,
>   fontSizes: ['12px', '14px', '16px', '18px'],
> ```

It's not quite clear where these values are coming from
___
*[src/components/AppBar/index.jsx, line 95 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIbGBK62v5fPIwjB07:-MmIbGBK62v5fPIwjB08:b-vqlqk3) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/index.jsx#L95)):*
> ```JavaScript
>           color: 'grey.700',
>           // less than modal (500)
>           zIndex: 400,
> ```

Can we avoid setting a z-index entirely? Or is this impossible because we have one on modal? Ideally, we wouldn't need to set any z-indices anywhere, but I'm not sure if that's possible here
___
*[src/components/AppBar/NavMenuItem.jsx, line 25 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIc4pLECsFLaK6xubn:-MmIc4pLECsFLaK6xubo:b-9y6xyg) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/NavMenuItem.jsx#L25)):*
> ```JavaScript
>         <Icon name={open ? 'chevronup' : 'chevrondown'} sx={{ ml: 2 }} />
>       </NavItem>
>       <DropdownMenuPrimitive.Content alignOffset={-4}>
> ```

What's the reason to style this differently than the default `DropdownMenu` items? On second thought, is this component even used in the Storybook example? I can't seem to find a menu item with a chevron that changes direction?
___
*[src/components/Avatar/index.jsx, line 24 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmId5cn5uHJUEYhkSuQ:-MmId5cn5uHJUEYhkSuR:b-o8401q) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/Avatar/index.jsx#L24)):*
> ```JavaScript
>       }}
>     >
>       {src ? (
> ```

Instead of dynamically switching, wouldn't it be safer to include fallback as a ...fallback? So that if image loading goes wrong we still have the initials in here.
___
*[src/components/Avatar/index.jsx, line 31 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIdaEY0YQg7_nPvnJn:-MmIdaEY0YQg7_nPvnJo:b-b6glwl) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/Avatar/index.jsx#L31)):*
> ```JavaScript
>             width: '100%',
>             height: '100%',
>             objectFit: 'cover',
> ```

IE11 doesn't support object-fit: cover;
___
*[src/components/LoremIpsum/index.jsx, line 24 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIeFDGEVhPdR7iZrUk:-MmIeFDGEVhPdR7iZrUl:bw2gqzq) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/LoremIpsum/index.jsx#L24)):*
> ```JavaScript
> ]
> 
> export default function LoremIpsum({ paragraphs: count }) {
> ```

I'm assuming this is just for illustration purposes inside Storybook? Can we move it to `src/component/private` please?
___
*[src/components/TextLinkButton/index.jsx, line 24 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIeY7lBb1-9hAErIjO:-MmIeY7lBb1-9hAErIjP:b-6y32kd) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/TextLinkButton/index.jsx#L24)):*
> ```JavaScript
>       isLoading={isLoading}
>       onKeyPress={handleKeyPress}
>       {...props}
> ```

Please don't spread all props but explicitly pass the ones you need. 
___
*[src/playground/Layout/index.stories.jsx, line 34 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIejP2BoqBCHqAmkdw:-MmIejP2BoqBCHqAmkdx:b-gksfuc) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/playground/Layout/index.stories.jsx#L34)):*
> ```JavaScript
> import { useResponsiveStyle } from '../../components/Hidden'
> 
> export default {
> ```

The playground is thus far only used for illustrative purposes and not quite for component documentation. Ideally, we'd have a `AppBar` story that somewhat shows how the component works. Having this playground is nice, too, though!


<!-- Sent from Reviewable.io -->

2021-10-18 15:23 UTC, phjardas reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 10 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

___
*[src/components/AppBar/context.jsx, line 18 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIa-s731bvk4nkeyXz:-MmIzDdfAztH_FPK63SA:b-tgm2en) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/context.jsx#L18)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

We rely on our components to use the closest ancestor `theme` passed by context. Accessing it directly like this bypasses this, which will lead to unexpected behavior. If the `breakpoints.collapseBelow` value is local to this component anyway, why do we need it in the theme?
</blockquote></details>

What's the correct way to do this then?
___
*[src/components/AppBar/index.jsx, line 95 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIbGBK62v5fPIwjB07:-MmIzHUh4jMPh5hJCWZA:b-ko2ssk) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/index.jsx#L95)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Can we avoid setting a z-index entirely? Or is this impossible because we have one on modal? Ideally, we wouldn't need to set any z-indices anywhere, but I'm not sure if that's possible here
</blockquote></details>

Modal has one, so I'm afraid we're stuck with setting it here as well. :-(
___
*[src/components/Avatar/index.jsx, line 24 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmId5cn5uHJUEYhkSuQ:-MmIzgs4AgLLeBuYmoIg:bbwbp3w) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/Avatar/index.jsx#L24)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Instead of dynamically switching, wouldn't it be safer to include fallback as a ...fallback? So that if image loading goes wrong we still have the initials in here.
</blockquote></details>

I'll have a look if I can replace it with the avatar from radix.
___
*[src/components/Avatar/index.jsx, line 31 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIdaEY0YQg7_nPvnJn:-MmIzjyW56H42jyqmOZV:bbwbp3w) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/Avatar/index.jsx#L31)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

IE11 doesn't support object-fit: cover;
</blockquote></details>

I'll have a look if I can replace it with the avatar from radix.


<!-- Sent from Reviewable.io -->

2021-10-18 15:37 UTC, gregoralbrecht reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 10 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

___
*[src/components/AppBar/context.jsx, line 18 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIa-s731bvk4nkeyXz:-MmJ2DEC4IcPYcHWu0fn:bow11x9) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/context.jsx#L18)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

What's the correct way to do this then?
</blockquote></details>

https://github.com/Qualifyze/design-system/blob/main/src/components/Modal/index.jsx#L44


<!-- Sent from Reviewable.io -->

2021-10-18 15:39 UTC, gregoralbrecht reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 10 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

___
*[src/components/AppBar/context.jsx, line 18 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIa-s731bvk4nkeyXz:-MmJ2JhQ6Dctu7Rb6Uns:b18qlhd) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/context.jsx#L18)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

https://github.com/Qualifyze/design-system/blob/main/src/components/Modal/index.jsx#L44
</blockquote></details>

FWIW I don't see why we'd need to make this configurable? Should we be fine with a global breakpoint for this? 


<!-- Sent from Reviewable.io -->

2021-10-19 08:52 UTC, phjardas reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 8 unresolved discussions (waiting on @gregoralbrecht)

___
*[src/components/AppBar/Button.jsx, line 51 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmI_f2v1uIQtRxxRegm:-MmMa33eDr0USjegkzGw:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/Button.jsx#L51)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

AFAIK buttons can't contain `div` so this needs to be a `span`. This also makes the button bigger
![image.png](https://files.reviewableusercontent.io/images/reviewable/6179211/8Xnf5dzAA_tqQjTjeCZeMPSV/image.png)

</blockquote></details>

Done.
___
*[src/components/AppBar/context.jsx, line 18 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIa-s731bvk4nkeyXz:-MmMaZ-g3MgYZStSRi58:bg6qf7l) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/context.jsx#L18)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

FWIW I don't see why we'd need to make this configurable? Should we be fine with a global breakpoint for this? 
</blockquote></details>

I like the flexibility, because it increases reusability. Same as the position (static or fixed)

From the example I can't find out how to get the theme into the actual component. I don't want to style it but require the theme inside the rendering function. Is there something like a `useTheme()` hook?
___
*[src/components/AppBar/index.jsx, line 79 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIbAmB-ymF6vFncUNi:-MmMa1COD4oazP74V5iS:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/index.jsx#L79)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

It's not quite clear where these values are coming from
</blockquote></details>

Done.
___
*[src/components/AppBar/NavMenuItem.jsx, line 25 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIc4pLECsFLaK6xubn:-MmMgTSG66x-kvjGdk3r:boe7eqf) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/NavMenuItem.jsx#L25)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

What's the reason to style this differently than the default `DropdownMenu` items? On second thought, is this component even used in the Storybook example? I can't seem to find a menu item with a chevron that changes direction?
</blockquote></details>

![menu.png](https://files.reviewableusercontent.io/images/reviewable/1437300/_U_6N4gs4-ivL1nin4y-KmBM/menu.png)

Because it would look different than the Figma template. And it doesn't work in the mobile view, where the dropdown menu isn't a dropdown at all.

I've fixed the usage of the chevron.

I really don't care. I just want to finish the discussion about how every detail is going to look like back and forth for more than a week now. It doesn't matter. Whatever we do here, we can change it one day later.
___
*[src/components/Avatar/index.jsx, line 24 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmId5cn5uHJUEYhkSuQ:-MmM_z7L54zACoQaa6GY:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/Avatar/index.jsx#L24)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

I'll have a look if I can replace it with the avatar from radix.
</blockquote></details>

Done.
___
*[src/components/Avatar/index.jsx, line 31 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIdaEY0YQg7_nPvnJn:-MmMVtC8BtlPnrHbvA35:b-orogcu) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/Avatar/index.jsx#L31)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

I'll have a look if I can replace it with the avatar from radix.
</blockquote></details>

Radix uses the same technique. Well, it does degrade somehow on IE11 but still works.
___
*[src/components/LoremIpsum/index.jsx, line 24 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIeFDGEVhPdR7iZrUk:-MmMbqkVDxZXJO3YKGXv:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/LoremIpsum/index.jsx#L24)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I'm assuming this is just for illustration purposes inside Storybook? Can we move it to `src/component/private` please?
</blockquote></details>

Done.
___
*[src/components/TextLinkButton/index.jsx, line 24 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIeY7lBb1-9hAErIjO:-MmMbrON0uRDB0Wq18TJ:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/TextLinkButton/index.jsx#L24)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Please don't spread all props but explicitly pass the ones you need. 
</blockquote></details>

Done.
___
*[src/playground/Layout/index.stories.jsx, line 34 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIejP2BoqBCHqAmkdw:-MmMbsbh5rjcQC3AA1AK:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/playground/Layout/index.stories.jsx#L34)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The playground is thus far only used for illustrative purposes and not quite for component documentation. Ideally, we'd have a `AppBar` story that somewhat shows how the component works. Having this playground is nice, too, though!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-19 09:18 UTC, gregoralbrecht requested changes
> Reviewed 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 5 unresolved discussions (waiting on @pablosci and @phjardas)

___
*[.changeset/lemon-ways-drop.md, line 5 at r4](https://reviewable.io/reviews/qualifyze/design-system/194#-MmMprpAD4fjxYaaA20m:-MmMprpAD4fjxYaaA20n:b-v427vq) ([raw file](https://github.com/qualifyze/design-system/blob/d0bfae0038a20a42f7ff714b78995fd3e608cc32/.changeset/lemon-ways-drop.md#L5)):*
> ```Markdown
> ---
> 
> Add new component: Menu (QC-1275)
> ```

Just seeing this now: Do we need two changesets? There's also `rude-pandas-tickle.md`
___
*[src/components/AppBar/Button.jsx, line 51 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmI_f2v1uIQtRxxRegm:-MmMlXBS535B-Ey0VtBB:b-a76wef) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/Button.jsx#L51)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The button with an icon is still bigger: 

With icon: 43px
Without icon: 40px
___
*[src/components/AppBar/context.jsx, line 18 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIa-s731bvk4nkeyXz:-MmMmCafCnkLfIsWhOre:bjq7hs1) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/context.jsx#L18)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

I like the flexibility, because it increases reusability. Same as the position (static or fixed)

From the example I can't find out how to get the theme into the actual component. I don't want to style it but require the theme inside the rendering function. Is there something like a `useTheme()` hook?
</blockquote></details>

Yup seems like it, but I don't think we expose it yet. Might make sense to do it, though: https://emotion.sh/docs/theming#withthemecomponent-reactcomponenttype-reactcomponenttype

The packages have been changed, because we're still using `emotion-theming`, but the functionality should be similar.
___
*[src/components/AppBar/index.jsx, line 79 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIbAmB-ymF6vFncUNi:-MmMmSZzELNksIv9wYJu:bs1wqwa) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/index.jsx#L79)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I meant was: As someone reading this I don't know where these values are coming from. A comment or something that explains this might be nice
___
*[src/components/AppBar/index.jsx, line 95 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIbGBK62v5fPIwjB07:-MmMma3g3V0Zz_QdpuzW:bfvno1c) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/index.jsx#L95)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Modal has one, so I'm afraid we're stuck with setting it here as well. :-(
</blockquote></details>

Darn :(
___
*[src/components/AppBar/index.stories.jsx, line 11 at r4](https://reviewable.io/reviews/qualifyze/design-system/194#-MmMmeSZ17tpS6DrTpPK:-MmMmeSZ17tpS6DrTpPL:b8rgg0w) ([raw file](https://github.com/qualifyze/design-system/blob/d0bfae0038a20a42f7ff714b78995fd3e608cc32/src/components/AppBar/index.stories.jsx#L11)):*
> ```JavaScript
> export default { title: 'AppBar' }
> 
> export const Default = () => {
> ```

Thank you! :100: 
___
*[src/components/AppBar/NavMenuItem.jsx, line 25 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIc4pLECsFLaK6xubn:-MmMnGMx81H_aas8imtW:b3qtbj9) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/NavMenuItem.jsx#L25)):*
> Because it would look different than the Figma template.

If the Figma mockup isn't aligned with our design system then we should challenge the mockup. I sent a suggestion to you and @pablosci and he was happy with it.

> And it doesn't work in the mobile view

Isn't this why we talked about making this two separate components? One for desktop and one for mobile. As opposed to having one that changes styles.

To be frank, I don't understand how you would like to proceed here. This is one huge PR with a bunch of changes. If you want to dismiss the reviews and just merge then feel free to do so. Personally, I don't believe this is ready to be released yet, which is why I'm leaving these comments. 
___
*[src/components/Avatar/index.jsx, line 31 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIdaEY0YQg7_nPvnJn:-MmMpHSzAPPTNqi60ZO5:b8d9y3z) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/Avatar/index.jsx#L31)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Radix uses the same technique. Well, it does degrade somehow on IE11 but still works.
</blockquote></details>

We spent a considerable amount of time making this DS work with IE11, so I 100% understand why the Radix team doesn't do the same. I suppose we can merge this because we don't have any avatar images anyway and as soon as we do we can fix this


<!-- Sent from Reviewable.io -->

2021-10-19 09:48 UTC, phjardas reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 5 unresolved discussions (waiting on @gregoralbrecht, @pablosci, and @phjardas)

___
*[.changeset/lemon-ways-drop.md, line 5 at r4](https://reviewable.io/reviews/qualifyze/design-system/194#-MmMprpAD4fjxYaaA20m:-MmMrU571WQeLtSKWizY:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/d0bfae0038a20a42f7ff714b78995fd3e608cc32/.changeset/lemon-ways-drop.md#L5)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Just seeing this now: Do we need two changesets? There's also `rude-pandas-tickle.md`
</blockquote></details>

Done.
___
*[src/components/AppBar/Button.jsx, line 51 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmI_f2v1uIQtRxxRegm:-MmMrcKu6dpz8Vb2fuZz:b-17861y) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/Button.jsx#L51)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The button with an icon is still bigger: 

With icon: 43px
Without icon: 40px
</blockquote></details>

Ooops. I have no idea what's happening here. Do you understand why the padding is larger?
___
*[src/components/AppBar/context.jsx, line 18 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIa-s731bvk4nkeyXz:-MmMsDQE8Znt2zDvo0rj:b-iv4z43) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/context.jsx#L18)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Yup seems like it, but I don't think we expose it yet. Might make sense to do it, though: https://emotion.sh/docs/theming#withthemecomponent-reactcomponenttype-reactcomponenttype

The packages have been changed, because we're still using `emotion-theming`, but the functionality should be similar.
</blockquote></details>

Works. Done.
___
*[src/components/AppBar/index.jsx, line 79 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIbAmB-ymF6vFncUNi:-MmMwame1S2xGG7Uu-S2:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/index.jsx#L79)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

What I meant was: As someone reading this I don't know where these values are coming from. A comment or something that explains this might be nice
</blockquote></details>

Done.
___
*[src/components/Avatar/index.jsx, line 31 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIdaEY0YQg7_nPvnJn:-MmMwqb_9kloJ7k7d4SJ:b-govv5d) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/Avatar/index.jsx#L31)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

We spent a considerable amount of time making this DS work with IE11, so I 100% understand why the Radix team doesn't do the same. I suppose we can merge this because we don't have any avatar images anyway and as soon as we do we can fix this
</blockquote></details>

Good idea. :-)


<!-- Sent from Reviewable.io -->

2021-10-19 09:55 UTC, phjardas reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: 30 of 35 files reviewed, 5 unresolved discussions (waiting on @gregoralbrecht, @pablosci, and @phjardas)

___
*[src/components/AppBar/NavMenuItem.jsx, line 25 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIc4pLECsFLaK6xubn:-MmMyB7y3KKreLkjgWUN:b-3l6oc8) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/NavMenuItem.jsx#L25)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

> Because it would look different than the Figma template.

If the Figma mockup isn't aligned with our design system then we should challenge the mockup. I sent a suggestion to you and @pablosci and he was happy with it.

> And it doesn't work in the mobile view

Isn't this why we talked about making this two separate components? One for desktop and one for mobile. As opposed to having one that changes styles.

To be frank, I don't understand how you would like to proceed here. This is one huge PR with a bunch of changes. If you want to dismiss the reviews and just merge then feel free to do so. Personally, I don't believe this is ready to be released yet, which is why I'm leaving these comments. 

</blockquote></details>

I think we agreed that we wanted to prevent having duplicate components if possible. :see_no_evil: That's why I introduced `<Menu />` as a list of options with decent styling, but independent of the location it's rendered in. The dropdown item from radix only works inside of a real dropdown. I'd have to duplicate the styling for the inline menu vs. the dropdown one, which I'd like to prevent. Do you have a better idea? I'm totally open for suggestions.


<!-- Sent from Reviewable.io -->

2021-10-19 15:46 UTC, gregoralbrecht approved these changes
As far as I can tell, it's not possible to "withdraw" a review, so I will "approve" in order not to block anyone.

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194#-:-MmODkNAAGe5g2V-bqUH:b-54ejmf)* status: all files reviewed, 1 unresolved discussion (waiting on @pablosci and @phjardas)

___
*[src/components/AppBar/Button.jsx, line 51 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmI_f2v1uIQtRxxRegm:-MmOC5lmC4H6_bgWUwkQ:b-7hm614) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/Button.jsx#L51)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Ooops. I have no idea what's happening here. Do you understand why the padding is larger?
</blockquote></details>

The icon is too big, probably fixable with a display: inline-flex or something like that
___
*[src/components/AppBar/NavMenuItem.jsx, line 25 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmIc4pLECsFLaK6xubn:-MmOCSRB6-TZvhjtf86S:biei0yi) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/NavMenuItem.jsx#L25)):*
>if possible

Seems like we've hit that wall we talked about because IMHO these would ideally be two separate components. There's no reason not to have keyboard support on desktop, for instance. It should be possible to have both of mobile and desktop components behind a single API but I'm not sure if that's desirable and easy to achieve.

On second thought, let me approve this PR simply because I currently lack the time to make more suggestions and I don't want to block anyone. 


<!-- Sent from Reviewable.io -->

2021-10-20 07:17 UTC, pablosci approved these changes

2021-10-21 08:49 UTC, sirJiggles approved these changes
> Reviewed 17 of 30 files at r1, 1 of 1 files at r2, 12 of 14 files at r4, 4 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)



<!-- Sent from Reviewable.io -->

2021-10-21 08:49 UTC, sirJiggles approved these changes
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)



<!-- Sent from Reviewable.io -->

2021-10-21 09:10 UTC, sirJiggles reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194#-:-MmX1nYcBfbxhE8xZ1MF:bnfp4nl)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht, @phjardas, and @sirJiggles)

___
*[src/components/AppBar/Button.jsx, line 51 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmI_f2v1uIQtRxxRegm:-MmX6CLC2zoDsKcOKQ44:b-406uo8) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/Button.jsx#L51)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The icon is too big, probably fixable with a display: inline-flex or something like that
</blockquote></details>

@gregoralbrecht a flex rather than a box seemed to fix her. let me know what you think then we can le merge this


<!-- Sent from Reviewable.io -->

2021-10-21 09:11 UTC, sirJiggles approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @phjardas)



<!-- Sent from Reviewable.io -->

2021-10-21 09:12 UTC, sirJiggles approved these changes
> Dismissed @gregoralbrecht from a discussion.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @phjardas)

___
*[src/components/AppBar/Button.jsx, line 51 at r3](https://reviewable.io/reviews/qualifyze/design-system/194#-MmI_f2v1uIQtRxxRegm:-MmX6tEd09cLhhhV7PBV:b-w13yiw) ([raw file](https://github.com/qualifyze/design-system/blob/b04ede220b05ad183b37aca8716b78fe1e17377b/src/components/AppBar/Button.jsx#L51)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

@gregoralbrecht a flex rather than a box seemed to fix her. let me know what you think then we can le merge this
</blockquote></details>

I will dismiss as I am sure it is cool now so I can continue. just ping me if not we can always make another branch 


<!-- Sent from Reviewable.io -->

2021-10-21 09:19 UTC, sirJiggles approved these changes
> Dismissed @phjardas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)



<!-- Sent from Reviewable.io -->

2021-10-21 09:19 UTC, sirJiggles approved these changes
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phjardas)



<!-- Sent from Reviewable.io -->

2021-10-21 09:19 UTC, merged