Stop using negative top margin on Stack
Qualifyze/design-system pull request #266
Opened 2022-02-10 13:49 UTC by jorgechiapello

# What❓

If space prop is 5, Stack component will overlap top component and won't allow to click it. 
Removed the margin top negative space and stop providing space to the first child stack Item.
This change should be backwards compatible since we don't change what the user expects or the API of the Stack component.

# Why 💁‍♀️
This negative margin generated layout issues and we have to adjust for the spacing of the first stack item.

# How to test ✅
1. Start Storybook
2. Go into Stack stories, look for 'with clickable content on top'
3. Pick any values for 'space' under 'Knobs' tab
4. Try to click the Button component

2022-02-10 13:49 UTC, gsuess commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualifyze/design-system/266)
<!-- Reviewable:end -->

2022-02-14 17:01 UTC, gregoralbrecht requested changes
Thanks for the PR! :100: 

I believe the negative margin is still more robust than specifically targeting the first item because it doesn't make assumptions about the items in the stack. We apply similar techniques to `<Inline>` and (if I'm not mistaken) other components. So in case negative margins are an issue, we need to tackle this on more than a single component. 

However, I feel like keeping the negative margins is the better way—but we do need to figure out why they are an issue and solve it with CSS instead. It works in Braid, so maybe we can look into why it works there and not for us.

https://github.com/seek-oss/braid-design-system/tree/7c776834dfb5bce6789845bfbf82bbd1776a45f8/lib/css/negativeMargin
https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8BlALgQzAawAQGcAHLGAXgB0QAbDAJwHMZKA%2BcgO11yQAUawYAFhCqxauATACW9AWlLAALAAYAvrgD0rDl14khImGInTZ85Ws3tOPPoOGjxUmXMWqNWpOvRZszECqA

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/266#-:-Mvcvku17cIPxgxykuhG:b-1jayxs)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jorgechiapello)



<!-- Sent from Reviewable.io -->

2022-02-14 21:24 UTC, jorgechiapello reviewed
I think I understand how they do it: they have a pseudo element `::before` with the negative margin (margin bottom by the way). I think that one is cleaner. I'll change as soon as I can.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/266#-:-Mvu6TPl5uJzGgDEe6Ht:b-dbxas0)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jorgechiapello)



<!-- Sent from Reviewable.io -->

2022-02-15 10:43 UTC, gregoralbrecht requested changes
The pseudo-element is not the important part. It's a little bit more involved than that, but I will have a PR ready soon.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/266#-:-MvwyYM633sgRoIaSUkU:ber02fs)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jorgechiapello)



<!-- Sent from Reviewable.io -->

2022-02-15 11:19 UTC, gregoralbrecht reviewed
I believe the fix in #270 works :) Please feel free to take a look and review

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/266#-:-Mvx5uK40VkC7FBgO4A5:b-310f2l)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jorgechiapello)



<!-- Sent from Reviewable.io -->

2022-02-17 15:35 UTC, closed without merging