VE-438 Use gap property instead of margins in Stack component
Qualifyze/design-system pull request #288
Opened 2022-04-07 11:44 UTC by jorgechiapello

# What❓

Use `gap` property for creating spaces in between child components of Stack. If we like it, we can roll out similar solutions to the other leaking components.

# Why 💁‍♀️

I think we can do a bit better to avoid leaking-prone components to generate problems, at least for most users (in our case, non Internet Explorer users).
New `gap` property provides same value while being making the component less prone to "leaking". 
Internet Explorer browsers doesn't support it, for which we keep old behavior.

# How to test ✅

1. Go to to the stories under "Stack", pick "leaking example".
2. Under tab "Knobs", untick "Using z-index".
3. Pick values for "Space" over `4`.
4. Try to click on the upper button, it should be clickable.

2022-04-07 11:44 UTC, gsuess commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualifyze/design-system/288)
<!-- Reviewable:end -->

2022-04-07 13:31 UTC, vubogovich reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/288)* status: all files reviewed, 1 unresolved discussion (waiting on @jorgechiapello)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/288#-N-3Cz1D5pJG9-_XeyRC:-N-3Cz1D5pJG9-_XeyRD:b-6623md) (no related file):*
Looks good. Curious if `:first-child` could help here for all the browsers though it might have some problems for IE 11.
https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child

---


<!-- Sent from Reviewable.io -->

2022-04-08 08:56 UTC, gregoralbrecht requested changes
There are some left-overs from IE11 support we should remove as well. Will provide details later! Also, let's merge all these changes into a separate branch until we're good to merge and then make this a minor release

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/288#-:-N-7NGcQ7iyBjjEzrbTy:b-jaeh2u)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @vubogovich)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/288#-N-3Cz1D5pJG9-_XeyRC:-N-7N1BDEzTvr2XucCuu:bjcddk) (no related file):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Looks good. Curious if `:first-child` could help here for all the browsers though it might have some problems for IE 11.
https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child
</blockquote></details>

It's not necessarily the first child

---


<!-- Sent from Reviewable.io -->

2022-04-08 10:36 UTC, vubogovich reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/288)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @vubogovich)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/288#-N-3Cz1D5pJG9-_XeyRC:-N-7jCu4Dhbtmd_ZlLlw:b-qskbkc) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

It's not necessarily the first child
</blockquote></details>

Isn't it assuming `Box` is a single element? What do I miss here?
Just curious, no need to support for IE 11 is anyway better :)

---


<!-- Sent from Reviewable.io -->

2022-04-08 10:39 UTC, gregoralbrecht reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/288)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @vubogovich)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/288#-N-3Cz1D5pJG9-_XeyRC:-N-7k-Kv5t9eL6NMfslb:bfr1z8g) (no related file):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Isn't it assuming `Box` is a single element? What do I miss here?
Just curious, no need to support for IE 11 is anyway better :)
</blockquote></details>

You mean "we could use first-child to remove the margin only from the first child", correct? The first child isn't necessarily visible so that doesn't work. That's not very apparent, I admit that, and it's currently not possible to hide elements in the stack I think. But still that makes it impossible to use first-child. There's also some issues with styling children in React if they're rendered dynamically

---


<!-- Sent from Reviewable.io -->

2022-04-14 15:30 UTC, gregoralbrecht requested changes
This PR can be closed in favor of #296  

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/288#-:-N-cgWon0R5ech-n8_un:b-pmp83k)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @jorgechiapello)



<!-- Sent from Reviewable.io -->

2022-04-14 16:37 UTC, closed without merging