VE-512 Add new tag design
Qualifyze/design-system pull request #313
Opened 2022-04-28 15:09 UTC by BartekQuali

# What❓

Updated tags to new design

# Why 💁‍♀️

We need new tag design

# How to test ✅

Use to component or check out preview at http://qualifyze-app-preview-1917.s3-website.eu-central-1.amazonaws.com/audit/recDRv5wqprV6Wd5V

# What was tested / affected 📝

Tag design

2022-04-28 15:10 UTC, gsuess commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualifyze/design-system/313)
<!-- Reviewable:end -->

2022-04-28 15:15 UTC, BartekQuali reviewed
@gregoralbrecht when doing such changes do we need to update the documentation and if so how I do it?

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313#-:-N0kjF284579ZFuWn6lJ:b-26doxf)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @gregoralbrecht)



<!-- Sent from Reviewable.io -->

2022-04-28 15:25 UTC, pablosci requested changes
Atm everything is looking good, thanks! just one small detail, can you add a simple background / color transition? 1s? if its complicated then avoid it

2022-04-28 15:40 UTC, BartekQuali reviewed
preview updated

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313#-:-N0kp7n85suVTuJSPUkx:bf0v266)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @gregoralbrecht)



<!-- Sent from Reviewable.io -->

2022-04-28 21:35 UTC, gregoralbrecht requested changes
Thanks for the PR! :trophy: 

Usually, each component has an accompanying "story" in Storybook that somewhat documents the behavior or at least shows how someone would use the component. For `Tag`, there's already a story but it's very basic and lacking some of the new props. I personally like to make different stories for different example usages (see `Actions` for examples), but it's also fine to control them with the "knobs" plugin in Storybook (see `Progressbar` for example).

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313#-:-N0m-AzJ09juWY8kfc5D:b-2vwnkn)* status: all files reviewed, 16 unresolved discussions (waiting on @BartekQuali and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m0dX796g9f0rJ9k71:-N0m0dX796g9f0rJ9k72:b-l3oggj) (no related file):*
Please run `npx changeset`, select "minor", use a descriptive release note and commit the resulting file to add a changeset to this PR. I believe it should be a minor release since we're adding new features.

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m19enCMNXEK9OHF7s:-N0m19eoD-jcqzZDzBC_:bee3kwa) (no related file):*
The new styling deviates from how it used to be, which is avoidable I think.

Before: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/6179211/Tsp8watHQ3yv-iLWBIQTzgVE/image.png)

Now:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/6179211/uQUpsCGdKDt7-wq_fLNa48SB/image.png)

This is a screenshot from the Storybook that gets deployed in each PR.

---
___
*[`src/components/Tag/index.jsx` line 23 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m1Qj3-Le5o5HshkCH:-N0m1Qj3-Le5o5HshkCI:bkucgmu) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L23)):*
> ```JavaScript
> const TagColors = {
>   info: {
>     content: theme.colors.primary[700],
> ```

If possible, we should avoid using the `theme` directly like this. All `styled` components can access the `theme` via `props.theme` and this ensures that changes to the theme will become available in all components. Basically: Use the theme passed by context and not by direct reference.
___
*[`src/components/Tag/index.jsx` line 54 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3RP4A4b--g4N5wa4:-N0m3RP4A4b--g4N5wa5:b-rj1zh2) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L54)):*
> ```JavaScript
> }
> 
> const Base = styled('div')((props) => ({
> ```

This will never be rendered as a `div` because you're setting the `as` prop to either `button` or the default `span`, so how come you change it to `div` here?
___
*[`src/components/Tag/index.jsx` line 56 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3iDa9dm4Q6GNqHPb:-N0m3iDb21z1QZMim8lS:b-tcly5n) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L56)):*
> ```JavaScript
> const Base = styled('div')((props) => ({
>   'position': 'relative',
>   'boxSizing': 'content-box',
> ```

Surprised to see this, is there a specific use case for that? Asking because I've never had to use `content-box`
___
*[`src/components/Tag/index.jsx` line 58 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3qal4RWr_Fuz2lQ5:-N0m3qal4RWr_Fuz2lQ6:bci1h58) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L58)):*
> ```JavaScript
>   'boxSizing': 'content-box',
>   'paddingRight': props.theme.space[2],
>   'paddingLeft': '0px',
> ```

`0` values should never have units I believe
___
*[`src/components/Tag/index.jsx` line 61 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m49EZ5lp6edgqfCtU:-N0m49EZ5lp6edgqfCtV:bacvtg0) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L61)):*
> ```JavaScript
>   'paddingTop': '0px',
>   'paddingBottom': '0px',
>   'whiteSpace': 'nowrap',
> ```

We might have to change that to accommodate long text, not sure will try 
___
*[`src/components/Tag/index.jsx` line 62 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3x6U8NVxUSBGG7el:-N0m3x6U8NVxUSBGG7em:b13evrr) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L62)):*
> ```JavaScript
>   'paddingBottom': '0px',
>   'whiteSpace': 'nowrap',
>   'height': props.tagSize.tagHeight,
> ```

Setting a height like this will probably break for tags with a lot of content. IMO it's better to achieve the desired height via padding instead of having a fixed height.
___
*[`src/components/Tag/index.jsx` line 70 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4GHM8UNZGkxonSBF:-N0m4GHM8UNZGkxonSBG:b-5qz8eh) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L70)):*
> ```JavaScript
>   'alignItems': 'center',
>   'border': 'none',
>   'transition': '1s',
> ```

This is definitely way too long. Will play around with possible values.
___
*[`src/components/Tag/index.jsx` line 73 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4KeE4sWVfcn8rziR:-N0m4KeE4sWVfcn8rziS:bo0vkn0) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L73)):*
> ```JavaScript
>   '&::after': {
>     content: '""',
>     boxSizing: 'content-box',
> ```

Same here, surprised to see `content-box`, what's its reason?
___
*[`src/components/Tag/index.jsx` line 87 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4QaB2DSc996sS0To:-N0m4QaB2DSc996sS0Tp:bpawxks) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L87)):*
> ```JavaScript
>     'color': props.color.content,
>     'marginLeft': props.theme.space[2],
>     'transition': '1s',
> ```

Same here, way too long.
___
*[`src/components/Tag/index.jsx` line 99 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4lRD8-8eUpLHHI3C:-N0m4lRD8-8eUpLHHI3D:baihc3h) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L99)):*
> ```JavaScript
>     },
>   },
>   '&:focus-visible': {
> ```

While `:focus-visible` is actually the better way to do this, we use `:focus` for the rest of the design system to make it work in IE11. We should probably keep doing that in this major version at least.
___
*[`src/components/Tag/index.jsx` line 100 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4yW_CrflCS4fPr4E:-N0m4yW_CrflCS4fPr4F:b-o8pr7e) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L100)):*
> ```JavaScript
>   },
>   '&:focus-visible': {
>     'border': '4px solid #478FE4',
> ```

Is this the focus ring? Search for `focusRing` in the DS to see other examples of how we apply it. Border is usually not a good idea because it changes the layout, that's why we use box-shadow
___
*[`src/components/Tag/index.jsx` line 157 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m2B-t1d8u3VgMdhpO:-N0m2B-t1d8u3VgMdhpP:bmmt1ti) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L157)):*
> ```JavaScript
>   icon: PropTypes.node,
>   trailingIcon: PropTypes.node,
>   color: PropTypes.object,
> ```

I have no idea why eslint is happy like this because locally this is a linter error for me. This prop is a `string` isn [...]

2022-04-28 22:05 UTC, gregoralbrecht commented
Here's a CSB with a basic reproduction of what's in Figma: https://codesandbox.io/s/qualifyze-design-system-basic--new-tag-design-olosg7?file=/src/App.js

2022-04-29 12:10 UTC, pablosci requested changes
Good job, it's looking good, minor details:

- maybe a 0.5s transition can do the trick
- is it me or the gray one does not have background color change on hover?

2022-04-29 12:56 UTC, gregoralbrecht commented
> Good job, it's looking good, minor details:
> 
> * maybe a 0.5s transition can do the trick
> * is it me or the gray one does not have background color change on hover?

IMO it's too early to do a design review, we need to finish the implementation and API first

2022-04-29 12:57 UTC, gregoralbrecht reviewed
IMO it's too early to do a design review, we need to finish the implementation and API first

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313#-:-N0pOVj_E8BF11g2pWCT:bkt1o7d)* status: all files reviewed, 16 unresolved discussions (waiting on @BartekQuali and @QuiqueQF)



<!-- Sent from Reviewable.io -->

2022-05-02 07:52 UTC, QuiqueQF approved these changes
I agree with @pablosci . Same comments. Thanks!

2022-05-02 09:08 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 61 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m49EZ5lp6edgqfCtU:-N130VPX4CDDcgDzikFk:ba8gvc) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L61)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

We might have to change that to accommodate long text, not sure will try 
</blockquote></details>

Currently design does not accommodate wrapped text so I would leave it as is. Imo wrapped text in tags is another story out of scope and I am not even sure that it's a behavior we would ever want in tags



_Code quote:_
```JavaScript
whiteSpace': 'nowrap
```


<!-- Sent from Reviewable.io -->

2022-05-02 09:09 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 62 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3x6U8NVxUSBGG7el:-N130s33BgRkhRI_yFjR:bg0va6w) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L62)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Setting a height like this will probably break for tags with a lot of content. IMO it's better to achieve the desired height via padding instead of having a fixed height.
</blockquote></details>

Can you elaborate? Is it linked to the wrap comment?


<!-- Sent from Reviewable.io -->

2022-05-02 09:09 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 70 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4GHM8UNZGkxonSBF:-N130xmZ19yfhoZFM2q6:b-7pgzcr) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L70)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This is definitely way too long. Will play around with possible values.
</blockquote></details>

Answered in the main thread


<!-- Sent from Reviewable.io -->

2022-05-02 09:09 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 87 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4QaB2DSc996sS0To:-N1317Yf1zKcxpojNhLC:b-7pgzcr) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L87)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Same here, way too long.
</blockquote></details>

Answered in the main thread


<!-- Sent from Reviewable.io -->

2022-05-02 09:13 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 73 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4KeE4sWVfcn8rziR:-N131cAO7bNh1CD5m6eF:bntsea5) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L73)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Same here, surprised to see `content-box`, what's its reason?
</blockquote></details>

So the reason here is that I can use width 100% and additional padding on top of that. 'border-box' would try to put that padding inside dimensions which I don't want


<!-- Sent from Reviewable.io -->

2022-05-02 09:26 UTC, gregoralbrecht requested changes
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313)* status: all files reviewed, 14 unresolved discussions (waiting on @BartekQuali and @gregoralbrecht)

___
*[`src/components/Tag/index.jsx` line 61 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m49EZ5lp6edgqfCtU:-N133g7i5YHxWbyoxIzH:b-hyfuw4) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L61)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Currently design does not accommodate wrapped text so I would leave it as is. Imo wrapped text in tags is another story out of scope and I am not even sure that it's a behavior we would ever want in tags
</blockquote></details>

Yeah fair point
___
*[`src/components/Tag/index.jsx` line 62 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3x6U8NVxUSBGG7el:-N133oDO50TovBgtIJcx:b-xutadg) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L62)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Can you elaborate? Is it linked to the wrap comment?
</blockquote></details>

If we don't want text wrapping in two lines this comment is obsolete now, will mark as resolved. Basically, fixed height in the DS is a red flag for me because it assumes fitting content, which isn't always the case. Height + padding is more defensive
___
*[`src/components/Tag/index.jsx` line 70 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4GHM8UNZGkxonSBF:-N133xV-5ZSJzkggRs8f:b-xq3dhi) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L70)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Answered in the main thread
</blockquote></details>

Let's try out some more values at the end when polishing everything. Everything above 400ms is too long IMO. 150/200ms might be fine, but let's discuss that later before merging
___
*[`src/components/Tag/index.jsx` line 73 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4KeE4sWVfcn8rziR:-N134QbnBobMxuz-URhN:bfev5wt) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L73)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

So the reason here is that I can use width 100% and additional padding on top of that. 'border-box' would try to put that padding inside dimensions which I don't want
</blockquote></details>

I find `border-box` a lot easier to reason with and I haven't had to use `content-box` in a long while, that's why I'm surprised here. Not a blocker really, but we even have a global CSS rule that set's everything to `box-sizing: border-box;` Can we avoid this here or is it really necessary?


<!-- Sent from Reviewable.io -->

2022-05-02 09:31 UTC, BartekQuali commented
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m0dX796g9f0rJ9k71:-N13661v9bFgx4uRoczw:b-896fix) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Please run `npx changeset`, select "minor", use a descriptive release note and commit the resulting file to add a changeset to this PR. I believe it should be a minor release since we're adding new features.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-05-02 09:32 UTC, BartekQuali reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313)* status: 0 of 2 files reviewed, 14 unresolved discussions (waiting on @BartekQuali and @gregoralbrecht)

___
*[`src/components/Tag/index.jsx` line 23 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m1Qj3-Le5o5HshkCH:-N1368_3AiCfxPsr4pFb:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L23)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

If possible, we should avoid using the `theme` directly like this. All `styled` components can access the `theme` via `props.theme` and this ensures that changes to the theme will become available in all components. Basically: Use the theme passed by context and not by direct reference.
</blockquote></details>

Done.
___
*[`src/components/Tag/index.jsx` line 54 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3RP4A4b--g4N5wa4:-N1369LuAmrAprDAz3hE:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L54)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This will never be rendered as a `div` because you're setting the `as` prop to either `button` or the default `span`, so how come you change it to `div` here?
</blockquote></details>

Done.
___
*[`src/components/Tag/index.jsx` line 58 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3qal4RWr_Fuz2lQ5:-N136A5XERGoDAsNKL2N:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L58)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

`0` values should never have units I believe
</blockquote></details>

Done.
___
*[`src/components/Tag/index.jsx` line 99 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4lRD8-8eUpLHHI3C:-N136JXACcmdf5Q-vuSU:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L99)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

While `:focus-visible` is actually the better way to do this, we use `:focus` for the rest of the design system to make it work in IE11. We should probably keep doing that in this major version at least.
</blockquote></details>

Done.
___
*[`src/components/Tag/index.jsx` line 100 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4yW_CrflCS4fPr4E:-N136L6P1kBzVzXTXf1D:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L100)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Is this the focus ring? Search for `focusRing` in the DS to see other examples of how we apply it. Border is usually not a good idea because it changes the layout, that's why we use box-shadow
</blockquote></details>

Done.
___
*[`src/components/Tag/index.jsx` line 157 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m2B-t1d8u3VgMdhpO:-N136Lue9cz9Uvz1haJW:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L157)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I have no idea why eslint is happy like this because locally this is a linter error for me. This prop is a `string` isn't it? Same with `size` below.
</blockquote></details>

Done.
___
*[`src/components/Tag/index.jsx` line 157 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m2rxR5wHi0L26vT3b:-N136MDX-8Cbcen1TKp3:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L157)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Let's use `tone` with the possible values we discussed (`neutral`, `critical` etc.):
```
tone: PropTypes.oneOf(['neutral', 'positive', 'critical', 'warning', 'info']),
```
</blockquote></details>

Done.
___
*[`src/components/Tag/index.jsx` line 158 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m2Lbn98Zvp9I_7CPu:-N136MSe4X_qc_hHxoDb:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L158)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Let's use `size` with the possible values `standard` (default) and `small`:
```
/** Size of the tag */
size: PropTypes.oneOf(['small', 'standard']),
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-02 09:34 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 73 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4KeE4sWVfcn8rziR:-N136aeTBNaM9ccS2R4g:b81gc3x) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L73)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I find `border-box` a lot easier to reason with and I haven't had to use `content-box` in a long while, that's why I'm surprised here. Not a blocker really, but we even have a global CSS rule that set's everything to `box-sizing: border-box;` Can we avoid this here or is it really necessary?
</blockquote></details>

I would need to use calc() function in css and I think content-box is better :) Unless you disagree? 


<!-- Sent from Reviewable.io -->

2022-05-02 09:37 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 56 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3iDa9dm4Q6GNqHPb:-N136mvR5JdU5aw_5GcD:b-v05mi0) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L56)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Surprised to see this, is there a specific use case for that? Asking because I've never had to use `content-box`
</blockquote></details>

This one could be probably removed. So the reason it is used it's to add a right margin to the last element in tag. But that would mean that the Base doesn't control all the padding between objects in it. Imho it's cleaner right now but if really don't wanna use this one it can be done without


<!-- Sent from Reviewable.io -->

2022-05-02 09:41 UTC, gregoralbrecht requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313)* status: all files reviewed, 8 unresolved discussions (waiting on @BartekQuali and @gregoralbrecht)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m19enCMNXEK9OHF7s:-N137LZj9vGew5jfhGBj:b3cr1l2) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The new styling deviates from how it used to be, which is avoidable I think.

Before: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/6179211/Tsp8watHQ3yv-iLWBIQTzgVE/image.png)

Now:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/6179211/uQUpsCGdKDt7-wq_fLNa48SB/image.png)

This is a screenshot from the Storybook that gets deployed in each PR.
</blockquote></details>

This is not resolved yet

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m0dX796g9f0rJ9k71:-N137TGy4o6zqwiaXFXv:b22ozqg) (no related file):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you commit the changeset? I'm not seeing it in the PR

---
___
*[`src/components/Tag/index.jsx` line 23 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m1Qj3-Le5o5HshkCH:-N137ZYn3zf17nzRhHi4:bas7rpo) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L23)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The function works fine, but I think we can stick to using `styled` components and variants for this, which would be more aligned with everything else. I'll open a PR with suggestions.
___
*[`src/components/Tag/index.jsx` line 73 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4KeE4sWVfcn8rziR:-N137voA-Iy96LFpp2MY:b-mxqqc2) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L73)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

I would need to use calc() function in css and I think content-box is better :) Unless you disagree? 
</blockquote></details>

Hm I'm having trouble following what that would be necessary, let me look at the code myself. I'd really like to avoid content-box
___
*[`src/components/Tag/index.jsx` line 100 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4yW_CrflCS4fPr4E:-N138C5N1BlYYm06Uca1:b-5drdpb) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L100)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The focus ring is animated by accident I believe. It "grows" but it should just appear.


<!-- Sent from Reviewable.io -->

2022-05-02 09:47 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 73 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4KeE4sWVfcn8rziR:-N139Z819PftLCdXZ0d7:b6eqntn) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L73)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Hm I'm having trouble following what that would be necessary, let me look at the code myself. I'd really like to avoid content-box
</blockquote></details>

Ok so basically what I want to achieve is 100% width + padding :)


<!-- Sent from Reviewable.io -->

2022-05-02 09:49 UTC, BartekQuali commented
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m0dX796g9f0rJ9k71:-N13A9gG-erHXTXahp8F:b-qmpnxy) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Did you commit the changeset? I'm not seeing it in the PR
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/103045141/m4CdElUiAQPOkeRUdAD3wEOE/image.png)
Reviewable hides it by default

---


<!-- Sent from Reviewable.io -->

2022-05-02 09:51 UTC, BartekQuali commented
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m0dX796g9f0rJ9k71:-N13AWkQ0LlXDiflOXas:b-velpg7) (no related file):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/103045141/m4CdElUiAQPOkeRUdAD3wEOE/image.png)
Reviewable hides it by default
</blockquote></details>

This is the only files `npx` changed

---


<!-- Sent from Reviewable.io -->

2022-05-02 09:51 UTC, BartekQuali commented
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m19enCMNXEK9OHF7s:-N13Aaup3t7eYiaMDDgI:bu9mg6a) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This is not resolved yet
</blockquote></details>

Yeah trying to figure out why does it behave this way

---


<!-- Sent from Reviewable.io -->

2022-05-02 09:55 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 56 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m3iDa9dm4Q6GNqHPb:-N13BaOC7vjqx2Kr4ZGm:bvo8rcw) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L56)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

This one could be probably removed. So the reason it is used it's to add a right margin to the last element in tag. But that would mean that the Base doesn't control all the padding between objects in it. Imho it's cleaner right now but if really don't wanna use this one it can be done without
</blockquote></details>

Nvm Removed


<!-- Sent from Reviewable.io -->

2022-05-02 10:11 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 23 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m1Qj3-Le5o5HshkCH:-N13F2tP5xbt5BTUEV-x:b-3qlheq) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L23)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The function works fine, but I think we can stick to using `styled` components and variants for this, which would be more aligned with everything else. I'll open a PR with suggestions.
</blockquote></details>

Sure I also iterated on this behaviour with moving the switch inside styled for cleaner code


<!-- Sent from Reviewable.io -->

2022-05-02 10:16 UTC, BartekQuali reviewed
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @BartekQuali and @gregoralbrecht)

___
*[`src/components/Tag/index.jsx` line 100 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4yW_CrflCS4fPr4E:-N13GLzo8HRKL69qFkZT:bt2vr1b) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L100)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The focus ring is animated by accident I believe. It "grows" but it should just appear.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2022-05-02 10:23 UTC, BartekQuali commented
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m19enCMNXEK9OHF7s:-N13HvahC7Uk0tiD7EWB:bayqoo9) (no related file):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Yeah trying to figure out why does it behave this way
</blockquote></details>

Flex is causing it :<

---


<!-- Sent from Reviewable.io -->

2022-05-02 10:23 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 70 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4GHM8UNZGkxonSBF:-N13I1yI8jNsf1pRCD5d:bqog80t) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L70)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Let's try out some more values at the end when polishing everything. Everything above 400ms is too long IMO. 150/200ms might be fine, but let's discuss that later before merging
</blockquote></details>

Agreed


<!-- Sent from Reviewable.io -->

2022-05-02 10:41 UTC, BartekQuali commented
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m19enCMNXEK9OHF7s:-N13M7F50sM4SU19lJGh:bt2vr0y) (no related file):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Flex is causing it :<
</blockquote></details>

Fixed!

---


<!-- Sent from Reviewable.io -->

2022-05-02 10:58 UTC, BartekQuali commented
@pablosci The grey does change color but it very subtle :) If it's so hard to see maybe we should adjust values in the design?





<!-- Sent from Reviewable.io -->

2022-05-02 12:08 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 23 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m1Qj3-Le5o5HshkCH:-N13f0T11Cm-S6wkoKXd:bkz50f9) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L23)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Sure I also iterated on this behaviour with moving the switch inside styled for cleaner code
</blockquote></details>

Fixed in your PR


<!-- Sent from Reviewable.io -->

2022-05-02 12:09 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 70 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4GHM8UNZGkxonSBF:-N13f5OX7YsZWHWxEW2S:bbldtna) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L70)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Fixed in your PR

Decided to remove transitions
 


<!-- Sent from Reviewable.io -->

2022-05-02 12:09 UTC, BartekQuali commented
*[`src/components/Tag/index.jsx` line 73 at r2](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m4KeE4sWVfcn8rziR:-N13f9EH6DTtmSutPYlu:b-v8kys1) ([raw file](https://github.com/qualifyze/design-system/blob/fe97980947e65432909892809f6753e913a86ecf/src/components/Tag/index.jsx#L73)):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

Ok so basically what I want to achieve is 100% width + padding :)
</blockquote></details>

Fixed in your PR
 


<!-- Sent from Reviewable.io -->

2022-05-02 12:14 UTC, gregoralbrecht requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313)* status: all files reviewed, 1 unresolved discussion (waiting on @BartekQuali and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m0dX796g9f0rJ9k71:-N13fuGm7oiKqNpQxk_V:b-9959fi) (no related file):*
<details><summary><i>Previously, BartekQuali wrote…</i></summary><blockquote>

This is the only files `npx` changed
</blockquote></details>

Try running `npx changese` it should show you a prompt like this: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/6179211/A_r2DDSpgJj0SyP2BTbX37Ox/image.png)

---


<!-- Sent from Reviewable.io -->

2022-05-02 12:20 UTC, BartekQuali commented
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/313#-N0m0dX796g9f0rJ9k71:-N13hnnD-TJrEHUnUnmH:b-896fix) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Try running `npx changese` it should show you a prompt like this: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/6179211/A_r2DDSpgJj0SyP2BTbX37Ox/image.png)

</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-05-02 12:21 UTC, gregoralbrecht approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/313#-:-N13htYR4RIbDWZpBa0g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pablosci)



<!-- Sent from Reviewable.io -->

2022-05-03 07:39 UTC, QuiqueQF reviewed
Ok.

2022-05-03 09:06 UTC, merged